import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useMeetingStore, loadRecords } from '@/stores/meetingStore'
import { useAuthStore } from '@/stores/authStore'
import type { MeetingRecord } from '@/types'
import { ArrowLeft, Clock, MessageSquare, FileText, Lock, Copy, CheckCircle, Download, FileDown } from 'lucide-react'

const electronAPI = (window as unknown as { electronAPI?: {
  export: { savePDF: (html: string, filename: string) => Promise<string | null> }
} }).electronAPI

/** 生成品牌化 PDF HTML */
function buildPDFHtml(record: MeetingRecord, showSummary: boolean): string {
  const title = record.meeting.title || 'Untitled Meeting'
  const date = new Date(record.meeting.created_at).toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  })
  const duration = `${Math.floor(record.meeting.duration_seconds / 60)}m ${record.meeting.duration_seconds % 60}s`

  const transcriptHtml = record.transcripts.map((t) => `
    <div style="margin-bottom:12px;">
      <span style="display:inline-block;padding:2px 8px;border-radius:4px;font-size:10px;font-weight:600;letter-spacing:0.05em;
        ${t.speaker === 'other' ? 'background:#FFF3CD;color:#856404;' : 'background:#D1ECF1;color:#0C5460;'}">
        ${t.speaker === 'other' ? 'INTERVIEWER' : 'CANDIDATE'}
      </span>
      <p style="margin:4px 0 0;font-size:13px;line-height:1.6;color:#333;">${t.text}</p>
    </div>
  `).join('')

  const answersHtml = record.answers.map((a) => `
    <div style="margin-bottom:16px;padding:12px;background:#F8F9FA;border-radius:8px;border-left:3px solid #FFD700;">
      <p style="font-size:11px;color:#666;margin:0 0 4px;">Q (${a.question_type}): ${a.question_text}</p>
      <p style="font-size:13px;color:#333;margin:0;line-height:1.5;">${a.answer_text}</p>
    </div>
  `).join('')

  const summaryHtml = showSummary && record.summary ? `
    <div style="page-break-before:always;">
      <h2 style="color:#FFD700;font-size:18px;border-bottom:2px solid #FFD700;padding-bottom:8px;">AI Meeting Summary</h2>
      <div style="font-size:13px;line-height:1.7;color:#333;white-space:pre-wrap;">${record.summary}</div>
    </div>
  ` : ''

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif; padding:40px; color:#222; }
    .header { display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:32px; padding-bottom:20px; border-bottom:2px solid #FFD700; }
    .logo { font-size:24px; font-weight:bold; }
    .logo span { color:#FFD700; }
    .meta { text-align:right; font-size:12px; color:#666; line-height:1.6; }
    h1 { font-size:22px; margin-bottom:4px; }
    h2 { font-size:18px; color:#FFD700; margin:24px 0 12px; border-bottom:1px solid #EEE; padding-bottom:8px; }
    .badge { display:inline-block; padding:3px 10px; border-radius:12px; font-size:11px; font-weight:600; background:#FFF3CD; color:#856404; margin-bottom:16px; }
    .footer { margin-top:40px; padding-top:16px; border-top:1px solid #EEE; text-align:center; font-size:10px; color:#999; }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="logo"><span>Vox</span>clar</div>
      <h1>${title}</h1>
      <span class="badge">${record.meeting.meeting_type.replace('_', ' ').toUpperCase()}</span>
    </div>
    <div class="meta">
      <div>${date}</div>
      <div>Duration: ${duration}</div>
      <div>Meeting ID: ${record.meeting.id.slice(0, 8)}</div>
    </div>
  </div>

  <h2>Full Transcript</h2>
  ${transcriptHtml}

  ${record.answers.length > 0 ? `<h2>AI-Generated Answers</h2>${answersHtml}` : ''}

  ${summaryHtml}

  <div class="footer">
    Generated by Voxclar — AI-Powered Interview Assistant<br>
    This document is confidential. Do not distribute without authorization.
  </div>
</body>
</html>`
}

function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60)
  const s = seconds % 60
  return `${m}m ${s}s`
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleString()
}

export default function MeetingRecordPage() {
  const navigate = useNavigate()
  const { lastRecord } = useMeetingStore()
  const user = useAuthStore((s) => s.user)
  const [records] = useState<MeetingRecord[]>(loadRecords)
  const [selectedId, setSelectedId] = useState<string | null>(lastRecord?.meeting.id || records[0]?.meeting.id || null)
  const [copied, setCopied] = useState(false)

  const isPremium = user?.subscription_tier && user.subscription_tier !== 'free'
  const record = selectedId
    ? (lastRecord?.meeting.id === selectedId ? lastRecord : records.find((r) => r.meeting.id === selectedId))
    : null

  const copyTranscript = () => {
    if (!record) return
    const text = record.transcripts.map((t) =>
      `[${t.speaker === 'other' ? 'Them' : 'You'}] ${t.text}`
    ).join('\n\n')
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const exportPDF = async () => {
    if (!record || !electronAPI) return
    const title = record.meeting.title || 'Untitled Meeting'
    const html = buildPDFHtml(record, isPremium)
    await electronAPI.export.savePDF(html, `Voxclar-${title.replace(/\s+/g, '_')}.pdf`)
  }

  const exportMarkdown = () => {
    if (!record) return
    const lines = [
      `# ${record.meeting.title || 'Untitled Meeting'}`,
      `> ${formatDate(record.meeting.created_at)} | ${formatDuration(record.meeting.duration_seconds)} | ${record.meeting.meeting_type}`,
      '', '## Transcript', '',
      ...record.transcripts.map((t) => `**[${t.speaker === 'other' ? 'Them' : 'You'}]** ${t.text}`),
      '', '## AI Answers', '',
      ...record.answers.map((a) => `**Q:** ${a.question_text}\n**A:** ${a.answer_text}\n`),
    ]
    if (record.summary && isPremium) {
      lines.push('', '## AI Summary', '', record.summary)
    }
    const blob = new Blob([lines.join('\n')], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `Voxclar-${(record.meeting.title || 'meeting').replace(/\s+/g, '_')}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="h-full flex gap-5">
      {/* Left: Meeting List */}
      <div className="w-64 flex-shrink-0 flex flex-col gap-2">
        <button
          onClick={() => navigate('/meeting')}
          className="flex items-center gap-2 text-sm text-imeet-text-secondary hover:text-imeet-gold transition-colors mb-2"
        >
          <ArrowLeft size={14} /> Back to Meeting
        </button>

        <h3 className="text-sm font-semibold text-imeet-gold mb-1">Meeting History</h3>

        <div className="flex-1 overflow-y-auto space-y-1.5">
          {records.length === 0 && (
            <p className="text-xs text-imeet-text-muted">No meetings yet</p>
          )}
          {records.map((r) => (
            <button
              key={r.meeting.id}
              onClick={() => setSelectedId(r.meeting.id)}
              className={`w-full text-left p-3 rounded-lg transition-all text-sm ${
                selectedId === r.meeting.id
                  ? 'bg-imeet-gold/10 border border-imeet-gold/30'
                  : 'bg-imeet-panel border border-imeet-border hover:border-imeet-border-light'
              }`}
            >
              <p className="font-medium truncate">{r.meeting.title || 'Untitled'}</p>
              <div className="flex items-center gap-2 mt-1 text-xs text-imeet-text-muted">
                <Clock size={10} />
                <span>{formatDuration(r.meeting.duration_seconds)}</span>
                <span className="capitalize">{r.meeting.meeting_type.replace('_', ' ')}</span>
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* Right: Record Detail */}
      <div className="flex-1 flex flex-col gap-4 min-w-0">
        {!record ? (
          <div className="flex-1 flex items-center justify-center text-imeet-text-muted">
            Select a meeting to view its record
          </div>
        ) : (
          <>
            {/* Header */}
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-bold">{record.meeting.title || 'Untitled Meeting'}</h2>
                <p className="text-xs text-imeet-text-muted">
                  {formatDate(record.meeting.created_at)} · {formatDuration(record.meeting.duration_seconds)} · {record.meeting.meeting_type.replace('_', ' ')}
                </p>
              </div>
              <div className="flex gap-2">
                <button
                  onClick={copyTranscript}
                  className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-all ${
                    copied ? 'bg-green-500/20 text-green-400' : 'bg-white/5 text-imeet-text-secondary hover:text-white'
                  }`}
                >
                  {copied ? <CheckCircle size={14} /> : <><Copy size={14} className="inline mr-1" />Copy</>}
                </button>
                <button
                  onClick={exportPDF}
                  className="px-3 py-1.5 rounded-lg text-xs font-medium bg-imeet-gold text-black hover:bg-imeet-gold-hover transition-all"
                >
                  <FileDown size={14} className="inline mr-1" />PDF
                </button>
                <button
                  onClick={exportMarkdown}
                  className="px-3 py-1.5 rounded-lg text-xs font-medium bg-white/5 text-imeet-text-secondary hover:text-white transition-all"
                >
                  <Download size={14} className="inline mr-1" />MD
                </button>
              </div>
            </div>

            {/* Transcript */}
            <div className="bg-imeet-panel rounded-[10px] p-5 border border-imeet-border flex-1 overflow-y-auto">
              <h3 className="text-sm font-semibold text-imeet-gold mb-3 flex items-center gap-2">
                <MessageSquare size={14} />
                Full Transcript
              </h3>
              <div className="space-y-3">
                {record.transcripts.map((t, i) => (
                  <div key={i}>
                    <span className={`text-[10px] px-1.5 py-0.5 rounded font-medium uppercase tracking-wider inline-block mb-1 ${
                      t.speaker === 'other' ? 'bg-amber-500/15 text-amber-400' : 'bg-blue-500/15 text-blue-400'
                    }`}>
                      {t.speaker === 'other' ? 'Them' : 'You'}
                    </span>
                    <p className="text-sm text-white/85 leading-relaxed">{t.text}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* AI Answers */}
            {record.answers.length > 0 && (
              <div className="bg-imeet-panel rounded-[10px] p-5 border border-imeet-border max-h-48 overflow-y-auto">
                <h3 className="text-sm font-semibold text-imeet-gold mb-3">AI Answers ({record.answers.length})</h3>
                <div className="space-y-3">
                  {record.answers.map((a, i) => (
                    <div key={i} className="bg-white/[0.03] rounded-lg p-3">
                      <p className="text-xs text-imeet-text-muted mb-1">Q: {a.question_text}</p>
                      <p className="text-sm whitespace-pre-wrap">{a.answer_text}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* AI Summary — Premium Only */}
            <div className="bg-imeet-panel rounded-[10px] p-5 border border-imeet-border">
              <h3 className="text-sm font-semibold text-imeet-gold mb-3 flex items-center gap-2">
                <FileText size={14} />
                AI Meeting Summary
                {!isPremium && (
                  <span className="flex items-center gap-1 text-[10px] bg-imeet-gold/10 text-imeet-gold px-2 py-0.5 rounded-full">
                    <Lock size={10} /> Premium
                  </span>
                )}
              </h3>

              {isPremium ? (
                record.summary ? (
                  <div className="prose prose-sm prose-invert max-w-none text-sm leading-relaxed whitespace-pre-wrap">
                    {record.summary}
                  </div>
                ) : record.summaryGenerating ? (
                  <p className="text-sm text-imeet-text-muted animate-pulse">Generating summary...</p>
                ) : (
                  <p className="text-sm text-imeet-text-muted">Summary will be generated after meeting ends</p>
                )
              ) : (
                <div className="text-center py-6">
                  <Lock size={24} className="mx-auto text-imeet-text-muted mb-2" />
                  <p className="text-sm text-imeet-text-muted mb-3">
                    AI meeting summaries are available on Basic, Standard, and Pro plans
                  </p>
                  <button
                    onClick={() => navigate('/subscription')}
                    className="bg-imeet-gold text-black font-semibold px-6 py-2 rounded-lg text-sm hover:bg-imeet-gold-hover active:scale-[0.98] transition-all"
                  >
                    Upgrade Plan
                  </button>
                </div>
              )}
            </div>
          </>
        )}
      </div>
    </div>
  )
}
